remote_theme: just-the-docs/just-the-docs


collections:
  Combinations:
    permalink: "/:collection/:path:output_ext"
    output: true
    
 
just_the_docs:
  collections:
    Combinations:
      name: Combinations
      nav_exclude: false
      nav_fold: true
      search_exclude: true
