remote_theme: just-the-docs/just-the-docs


collections:
  combinations:
    permalink: "/:collection/:path:output_ext"
    output: true
  ds:
    permalink: "/:collection/:path:output_ext"
    output: true  
  impl:
    permalink: "/:collection/:path:output_ext"
    output: true  
  java:
    permalink: "/:collection/:path:output_ext"
    output: true
  test:
    permalink: "/:collection/:path:output_ext"
    output: true  



just_the_docs:
  collections:
    combinations:
      name: Combinations
      nav_exclude: false
      nav_fold: false
      search_exclude: false
    ds:
      name: Data Structures
      nav_exclude: false
      nav_fold: false
      search_exclude: false
    impl:
      name: Implementations
      nav_exclude: false
      nav_fold: false
      search_exclude: false
    java:
      name: Java
      nav_exclude: false
      nav_fold: false
      search_exclude: false
    test:
      name: Test
      nav_exclude: false
      nav_fold: false
      search_exclude: false  